/**
 * The generated PreToolUse hook script.
 *
 * `~/.poseidon/bin/cmd-hook.mjs` is a dependency-free node script the harness
 * runs through the system shell for every tool call while Poseidon is driving.
 * It reads the hook payload on stdin, POSTs it to the server's HookBridge with
 * the per-session bearer, and prints the bridge's `hookSpecificOutput` back so
 * the harness applies the decision. Every failure path — bridge down, timeout,
 * garbage response — prints a `deny`: a hook that cannot reach the bridge must
 * never accidentally let a mutation through.
 *
 * **The bearer arrives in a file, not in the environment.** Command Code
 * redacts secret-shaped variable names out of the environment it hands a hook:
 * a live run showed `POSEIDON_HOOK_URL` and `POSEIDON_THREAD_ID` arriving while
 * `POSEIDON_HOOK_TOKEN`, `..._BEARER`, `..._SECRET`, `..._AUTH`, `..._PASSWORD`
 * and `..._CREDENTIAL` were all stripped — sensible of it, and fatal for us:
 * the script took its "no session owns this run" path and exited silently, the
 * harness fell back to its own flow, and under `--yolo` that means every tool
 * call ran unapproved. Dodging the denylist by picking a name it does not
 * recognize yet would make the entire approval gate depend on a heuristic we
 * do not control, so the env carries a *path* (`POSEIDON_HOOK_TICKET_FILE`) and
 * the bearer lives in a 0600 file the session writes and deletes.
 * `POSEIDON_HOOK_TOKEN` is still read when it survives, so a harness that does
 * not redact needs no file.
 *
 * One exception: the hook block we install into a project's
 * `.commandcode/settings.local.json` outlives the session that wrote it, so an
 * interactive `cmd` run in that project invokes the script without
 * `POSEIDON_HOOK_URL`/`POSEIDON_HOOK_TOKEN`. That run belongs to the user, not to
 * us — the script exits cleanly with NO output rather than deny every tool call
 * forever, and the harness falls back to its own prompt flow. Our spawned
 * sessions always carry the env, so deny-on-unreachable still applies to them.
 *
 * The script is regenerated only when its content hash differs, so a session
 * start does not churn the file (and a running `cmd` never reads a half-written
 * script).
 */

import * as NodeCrypto from "node:crypto";
import * as NodeFS from "node:fs";
import * as NodePath from "node:path";
import { binDir } from "@poseidon/shared/paths";
import * as Effect from "effect/Effect";

export const HOOK_SCRIPT_NAME = "cmd-hook.mjs";

/** Where the hook script lives. `env` is for tests pointing POSEIDON_HOME aside. */
export const hookScriptPath = (env?: Readonly<Record<string, string | undefined>>): string =>
  NodePath.join(binDir(env), HOOK_SCRIPT_NAME);

/**
 * Where a session's bearer waits for its hook: `~/.poseidon/bin/tickets/<id>`,
 * mode 0600, written when the session opens and deleted when it closes.
 */
export const hookTicketPath = (
  threadId: string,
  env?: Readonly<Record<string, string | undefined>>,
): string => NodePath.join(binDir(env), "tickets", `${threadId}.ticket`);

/** Writes the ticket readable only by its owner, replacing any stale one. */
export const writeHookTicket = (path: string, bearer: string): Effect.Effect<void> =>
  Effect.sync(() => {
    NodeFS.mkdirSync(NodePath.dirname(path), { recursive: true, mode: 0o700 });
    const tmp = `${path}.${process.pid}.${NodeCrypto.randomUUID()}.tmp`;
    NodeFS.writeFileSync(tmp, bearer, { encoding: "utf8", mode: 0o600 });
    NodeFS.renameSync(tmp, path);
  });

export const removeHookTicket = (path: string): Effect.Effect<void> =>
  Effect.sync(() => {
    try {
      NodeFS.rmSync(path, { force: true });
    } catch {
      // Already gone, or a home directory that vanished under us.
    }
  });

/**
 * Plain node, no imports, no dependencies. Keep it synchronous and boring: it
 * runs once per tool call, inside the harness's own hook machinery.
 */
export const hookScriptSource = (): string => `#!/usr/bin/env node
// Generated by Poseidon — do not edit. Answers Command Code PreToolUse hooks
// by POSTing the payload to the Poseidon server; deny on any failure.
import * as fs from "node:fs";

const TIMEOUT_MS = 570000; // under the 590s bridge ceiling and the 600s hook cap

// The bearer comes from a file the session wrote: Command Code strips
// secret-shaped names (TOKEN, BEARER, SECRET, AUTH, PASSWORD, CREDENTIAL) out
// of a hook's environment. The env variable that survives is a path.
const bearer = () => {
  const direct = process.env.POSEIDON_HOOK_TOKEN;
  if (direct !== undefined && direct !== "") {
    return direct;
  }
  const file = process.env.POSEIDON_HOOK_TICKET_FILE;
  if (file === undefined || file === "") {
    return undefined;
  }
  try {
    const text = fs.readFileSync(file, "utf8").trim();
    return text === "" ? undefined : text;
  } catch {
    return undefined;
  }
};

const deny = (reason) => {
  process.stdout.write(
    JSON.stringify({
      hookSpecificOutput: { permissionDecision: "deny", permissionDecisionReason: reason },
    }) + "\\n",
  );
};

const readStdin = () =>
  new Promise((resolve, reject) => {
    let data = "";
    process.stdin.setEncoding("utf8");
    process.stdin.on("data", (chunk) => {
      data += chunk;
    });
    process.stdin.on("end", () => resolve(data));
    process.stdin.on("error", reject);
  });

const main = async () => {
  const url = process.env.POSEIDON_HOOK_URL;
  const token = bearer();
  if (url === undefined || url === "" || token === undefined || token === "") {
    // No Poseidon session owns this run — an interactive cmd in a project
    // whose settings still carry our hook block. Emit NO decision: a clean
    // exit with empty stdout hands the call back to the harness's own
    // prompt flow instead of denying it.
    return;
  }
  const input = await readStdin();
  let text;
  try {
    const response = await fetch(url, {
      method: "POST",
      headers: { "content-type": "application/json", authorization: "Bearer " + token },
      body: input,
      signal: AbortSignal.timeout(TIMEOUT_MS),
    });
    text = await response.text();
    if (!response.ok) {
      return deny("hook bridge answered " + response.status);
    }
  } catch (error) {
    return deny("hook bridge unreachable: " + ((error && error.message) || String(error)));
  }
  try {
    const parsed = JSON.parse(text);
    if (parsed && typeof parsed === "object" && parsed.hookSpecificOutput) {
      process.stdout.write(JSON.stringify(parsed) + "\\n");
    } else {
      deny("hook bridge returned an unexpected body");
    }
  } catch {
    deny("hook bridge returned invalid JSON");
  }
};

main().then(
  () => process.exit(0),
  (error) => {
    deny(String(error));
    process.exit(0);
  },
);
`;

const hash = (content: string): string =>
  NodeCrypto.createHash("sha256").update(content, "utf8").digest("hex");

/**
 * Writes the hook script (mode 0700 — the shell executes it directly) and
 * returns its path. Rewrites only when the content hash differs, so a warm
 * start is a stat, not a write.
 */
export const ensureHookScript = (
  env?: Readonly<Record<string, string | undefined>>,
): Effect.Effect<string> =>
  Effect.sync(() => {
    const path = hookScriptPath(env);
    const source = hookScriptSource();
    const wanted = hash(source);
    let current: string | null = null;
    try {
      current = hash(NodeFS.readFileSync(path, "utf8"));
    } catch {
      current = null;
    }
    if (current !== wanted) {
      NodeFS.mkdirSync(NodePath.dirname(path), { recursive: true });
      // temp + rename: a running `cmd` must never read a half-written script.
      const tmp = `${path}.${process.pid}.${NodeCrypto.randomUUID()}.tmp`;
      NodeFS.writeFileSync(tmp, source, { encoding: "utf8", mode: 0o700 });
      NodeFS.renameSync(tmp, path);
    }
    NodeFS.chmodSync(path, 0o700);
    return path;
  });
