/**
 * The generated PreToolUse hook script (spec sections 5.5 and 8).
 *
 * `~/.openade/bin/cmd-hook.mjs` is a dependency-free node script the harness
 * runs through the system shell for every tool call while OpenAde is driving.
 * It reads the hook payload on stdin, POSTs it to the server's HookBridge with
 * the per-session bearer, and prints the bridge's `hookSpecificOutput` back so
 * the harness applies the decision. Every failure path — bridge down, timeout,
 * garbage response — prints a `deny`: a hook that cannot reach the bridge must
 * never accidentally let a mutation through.
 *
 * The script is regenerated only when its content hash differs, so a session
 * start does not churn the file (and a running `cmd` never reads a half-written
 * script).
 */

import * as NodeCrypto from "node:crypto";
import * as NodeFS from "node:fs";
import * as NodePath from "node:path";
import { binDir } from "@OpenAde/shared/paths";
import * as Effect from "effect/Effect";

export const HOOK_SCRIPT_NAME = "cmd-hook.mjs";

/** Where the hook script lives. `env` is for tests pointing OPENADE_HOME aside. */
export const hookScriptPath = (env?: Readonly<Record<string, string | undefined>>): string =>
  NodePath.join(binDir(env), HOOK_SCRIPT_NAME);

/**
 * Plain node, no imports, no dependencies. Keep it synchronous and boring: it
 * runs once per tool call, inside the harness's own hook machinery.
 */
export const hookScriptSource = (): string => `#!/usr/bin/env node
// Generated by OpenAde — do not edit. Answers Command Code PreToolUse hooks
// by POSTing the payload to the OpenAde server; deny on any failure.
const TIMEOUT_MS = 570000; // under the 590s bridge ceiling and the 600s hook cap

const deny = (reason) => {
  process.stdout.write(
    JSON.stringify({
      hookSpecificOutput: { permissionDecision: "deny", permissionDecisionReason: reason },
    }) + "\\n",
  );
};

const readStdin = () =>
  new Promise((resolve, reject) => {
    let data = "";
    process.stdin.setEncoding("utf8");
    process.stdin.on("data", (chunk) => {
      data += chunk;
    });
    process.stdin.on("end", () => resolve(data));
    process.stdin.on("error", reject);
  });

const main = async () => {
  const url = process.env.OPENADE_HOOK_URL;
  const token = process.env.OPENADE_HOOK_TOKEN;
  const input = await readStdin();
  if (url === undefined || url === "" || token === undefined || token === "") {
    return deny("openade hook bridge is not configured");
  }
  let text;
  try {
    const response = await fetch(url, {
      method: "POST",
      headers: { "content-type": "application/json", authorization: "Bearer " + token },
      body: input,
      signal: AbortSignal.timeout(TIMEOUT_MS),
    });
    text = await response.text();
    if (!response.ok) {
      return deny("hook bridge answered " + response.status);
    }
  } catch (error) {
    return deny("hook bridge unreachable: " + ((error && error.message) || String(error)));
  }
  try {
    const parsed = JSON.parse(text);
    if (parsed && typeof parsed === "object" && parsed.hookSpecificOutput) {
      process.stdout.write(JSON.stringify(parsed) + "\\n");
    } else {
      deny("hook bridge returned an unexpected body");
    }
  } catch {
    deny("hook bridge returned invalid JSON");
  }
};

main().then(
  () => process.exit(0),
  (error) => {
    deny(String(error));
    process.exit(0);
  },
);
`;

const hash = (content: string): string =>
  NodeCrypto.createHash("sha256").update(content, "utf8").digest("hex");

/**
 * Writes the hook script (mode 0700 — the shell executes it directly) and
 * returns its path. Rewrites only when the content hash differs, so a warm
 * start is a stat, not a write.
 */
export const ensureHookScript = (
  env?: Readonly<Record<string, string | undefined>>,
): Effect.Effect<string> =>
  Effect.sync(() => {
    const path = hookScriptPath(env);
    const source = hookScriptSource();
    const wanted = hash(source);
    let current: string | null = null;
    try {
      current = hash(NodeFS.readFileSync(path, "utf8"));
    } catch {
      current = null;
    }
    if (current !== wanted) {
      NodeFS.mkdirSync(NodePath.dirname(path), { recursive: true });
      NodeFS.writeFileSync(path, source, { encoding: "utf8", mode: 0o700 });
    }
    NodeFS.chmodSync(path, 0o700);
    return path;
  });
